compras/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = [

    url(regex=r'^solicitudes/$',
        view=views.SolicitudDeCompraList.as_view(),
        name='lista_solicitudes'
        ),

    url(regex=r'^solicitudes/nueva$',
        view=views.solicitud_de_compra_cru,
        name='nueva_solicitud'
        ),

    url(regex=r'^solicitudes/(?P<pk>[\w-]+)/editar/$',
        view=views.solicitud_de_compra_cru,
        name='editar_solicitud'
        ),

    url(regex=r'^solicitudes/(?P<pk>[\w-]+)/$',
        view=views.detalle_solicitud_de_compra,
        name='detalle_solicitud'
        ),

    url(regex=r'^solicitudes/(?P<pk>[\w-]+)/borrar/$',
        view=views.BorrarSolicitudDeCompra.as_view(),
        name='borrar_solicitud'
        ),

    url(regex=r'^solicitudes/(?P<pk>[\w-]+)/aprobar/$',
        view=views.AprobarSolicitudDeCompra.as_view(),
        name='aprobar_solicitud'
        ),

    url(regex=r'^cotizaciones/$',
        view=views.CotizacionesList.as_view(),
        name='lista_cotizaciones'
        ),

    url(regex=r'^cotizaciones/nueva/$',
        view=views.cotizacion_cru,
        name='nueva_cotizacion'
        ),

    url(regex=r'^cotizaciones/(?P<pk>[\w-]+)/editar/$',
        view=views.cotizacion_cru,
        name='editar_cotizacion'
        ),

    url(regex=r'^cotizaciones/(?P<pk>[\w-]+)/$',
        view=views.detalle_cotizacion,
        name='detalle_cotizacion'
        ),

    url(regex=r'^cotizaciones/(?P<pk>[\w-]+)/borrar/$',
        view=views.BorrarCotizacion.as_view(),
        name='borrar_cotizacion'
        ),

    url(regex=r'^cotizaciones/(?P<pk>[\w-]+)/aprobar/$',
        view=views.AprobarCotizacion.as_view(),
        name='aprobar_cotizacion'
        ),

    url(regex=r'^cotizaciones/(?P<pk>[\w-]+)/rechazar/$',
        view=views.RechazarCotizacion.as_view(),
        name='rechazar_cotizacion'
        ),

    url(regex=r'^ordenes/$',
        view=views.OrdenesList.as_view(),
        name='lista_ordenes'
        ),

    url(regex=r'^ordenes/nueva/$',
        view=views.orden_de_compra_cru,
        name='nueva_orden'
        ),

    url(regex=r'^ordenes/(?P<pk>[\w-]+)/$',
        view=views.detalle_orden,
        name='detalle_orden'
        ),

    url(regex=r'^ordenes/(?P<pk>[\w-]+)/editar/$',
        view=views.orden_de_compra_cru,
        name='editar_orden'
        ),

    url(regex=r'^ordenes/(?P<pk>[\w-]+)/borrar/$',
        view=views.BorrarOrdenDeCompra.as_view(),
        name='borrar_orden'
        ),

    url(regex=r'^facturas/$',
        view=views.FacturasList.as_view(),
        name='lista_facturas'
        ),

    url(regex=r'^facturas/nueva/$',
        view=views.CrearFactura.as_view(),
        name='nueva_factura'
        ),

    url(regex=r'^facturas/(?P<pk>[\w-]+)/$',
        view=views.DetalleFactura.as_view(),
        name='detalle_factura'
        ),

    url(regex=r'^facturas/(?P<pk>[\w-]+)/editar/$',
        view=views.ActualizarFactura.as_view(),
        name='editar_factura'
        ),

    url(regex=r'^facturas/(?P<pk>[\w-]+)/borrar/$',
        view=views.BorrarFactura.as_view(),
        name='borrar_factura'
        ),
]

contactos/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = [

    url(regex=r'^nuevo/$',
        view=views.contacto_cru,
        name='nuevo'
        ),

    url(regex=r'^(?P<uuid>[\w-]+)/editar/$',
        view=views.contacto_cru,
        name='editar'
        ),

    url(regex=r'^(?P<pk>[\w-]+)/borrar/$',
        view=views.BorrarContacto.as_view(),
        name='borrar'
        ),

    url(regex=r'^(?P<uuid>[\w-]+)/$',
        view=views.detalle_contacto,
        name='detalle'
        ),

]

mercaderias/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = [

    url(regex=r'^$',
        view=views.MercaderiasList.as_view(),
        name='lista'
        ),

    url(regex=r'^nuevo/$',
        view=views.mercaderias_create,
        name='nuevo'
        ),

    url(regex=r'^(?P<pk>[\w-]+)/editar/$',
        view=views.mercaderias_edit,
        name='editar'
        ),

    url(regex=r'^(?P<pk>[\w-]+)/borrar/$',
        view=views.EliminarMercaderia.as_view(),
        name='borrar'
        ),

    url(regex=r'^categorias/$',
        view=views.CategoriasList.as_view(),
        name='lista_categorias'
        ),

    url(regex=r'^categorias/nuevo/$',
        view=views.CrearCategoria.as_view(),
        name='nueva_categoria'
        ),

    url(regex=r'^categorias/(?P<pk>[\w-]+)/editar/$',
        view=views.ActualizarCategoria.as_view(),
        name='editar_categoria'
        ),

    url(regex=r'^categorias/(?P<pk>[\w-]+)/borrar/$',
        view=views.EliminarCategoria.as_view(),
        name='borrar_categoria'
        ),

]

proj_compras/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings


admin.autodiscover()


urlpatterns = patterns(
    '',

    url(r'^admin/', include(admin.site.urls)),

    #login-users
    url(r'^',
        include('usuarios.urls',  namespace='usuarios')
        ),

    # Login/Logout URLs
    #(r'^login/$',
    #    'django.contrib.auth.views.login', {'template_name': 'login.html'}
    #),

    #(r'^logout/$',
    #    'django.contrib.auth.views.logout', {'next_page': '/login/'}
    #),

    url(r'^proveedores/',
        include('proveedores.urls', namespace='proveedores')
        ),

    url(r'^contactos/',
        include('contactos.urls', namespace='contactos')
        ),

    url(r'^mercaderias/',
        include('mercaderias.urls', namespace='mercaderias')
        ),

    url(r'^compras/',
        include('compras.urls', namespace='compras')
        ),
)
#Added for debug toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

usuarios/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    url(regex=r'^$',
        view=views.user_login,
        name='login'
        ),

    url(regex=r'^logout/$',
        view=views.user_logout,
        name='logout'
        ),

#principal
    #url(r'^home', Home.as_view(), name='home'),
]

proj_compras/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{% block title %}{% endblock title %}</title></head>
    {% block css %}{% endblock css %}
 <body class="hold-transition skin-blue sidebar-mini">

    {% block content %}
    {% endblock content %}

    {% block js %}
    {% endblock js %}
</html>

proj_compras/templates/footer.html
 <footer class="main-footer">
        <div class="pull-right hidden-xs">
          <b>Version</b> 0.1
        </div>
      </footer>

      <!-- Control Sidebar -->
      <aside class="control-sidebar control-sidebar-dark">
        <!-- Create the tabs -->
        <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
          <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
          <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
          <!-- Home tab content -->
          <div class="tab-pane" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class="control-sidebar-menu">
              <li>
                <a href="javascript::;">
                  <i class="menu-icon fa fa-birthday-cake bg-red"></i>
                  <div class="menu-info">
                    <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>
                    <p>Will be 23 on April 24th</p>
                  </div>
                </a>
              </li>
              <li>
                <a href="javascript::;">
                  <i class="menu-icon fa fa-user bg-yellow"></i>
                  <div class="menu-info">
                    <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>
                    <p>New phone +1(800)555-1234</p>
                  </div>
                </a>
              </li>
              <li>
                <a href="javascript::;">
                  <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>
                  <div class="menu-info">
                    <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>
                    <p>nora@example.com</p>
                  </div>
                </a>
              </li>
              <li>
                <a href="javascript::;">
                  <i class="menu-icon fa fa-file-code-o bg-green"></i>
                  <div class="menu-info">
                    <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>
                    <p>Execution time 5 seconds</p>
                  </div>
                </a>
              </li>
            </ul><!-- /.control-sidebar-menu -->

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class="control-sidebar-menu">
              <li>
                <a href="javascript::;">
                  <h4 class="control-sidebar-subheading">
                    Custom Template Design
                    <span class="label label-danger pull-right">70%</span>
                  </h4>
                  <div class="progress progress-xxs">
                    <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                  </div>
                </a>
              </li>
              <li>
                <a href="javascript::;">
                  <h4 class="control-sidebar-subheading">
                    Update Resume
                    <span class="label label-success pull-right">95%</span>
                  </h4>
                  <div class="progress progress-xxs">
                    <div class="progress-bar progress-bar-success" style="width: 95%"></div>
                  </div>
                </a>
              </li>
              <li>
                <a href="javascript::;">
                  <h4 class="control-sidebar-subheading">
                    Laravel Integration
                    <span class="label label-warning pull-right">50%</span>
                  </h4>
                  <div class="progress progress-xxs">
                    <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
                  </div>
                </a>
              </li>
              <li>
                <a href="javascript::;">
                  <h4 class="control-sidebar-subheading">
                    Back End Framework
                    <span class="label label-primary pull-right">68%</span>
                  </h4>
                  <div class="progress progress-xxs">
                    <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                  </div>
                </a>
              </li>
            </ul><!-- /.control-sidebar-menu -->

          </div><!-- /.tab-pane -->
          <!-- Stats tab content -->
          <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div><!-- /.tab-pane -->
          <!-- Settings tab content -->
          <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
              <h3 class="control-sidebar-heading">General Settings</h3>
              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Report panel usage
                  <input type="checkbox" class="pull-right" checked>
                </label>
                <p>
                  Some information about this general settings option
                </p>
              </div><!-- /.form-group -->

              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Allow mail redirect
                  <input type="checkbox" class="pull-right" checked>
                </label>
                <p>
                  Other sets of options are available
                </p>
              </div><!-- /.form-group -->

              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Expose author name in posts
                  <input type="checkbox" class="pull-right" checked>
                </label>
                <p>
                  Allow the user to show his name in blog posts
                </p>
              </div><!-- /.form-group -->

              <h3 class="control-sidebar-heading">Chat Settings</h3>

              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Show me as online
                  <input type="checkbox" class="pull-right" checked>
                </label>
              </div><!-- /.form-group -->

              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Turn off notifications
                  <input type="checkbox" class="pull-right">
                </label>
              </div><!-- /.form-group -->

              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Delete chat history
                  <a href="javascript::;" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                </label>
              </div><!-- /.form-group -->
            </form>
          </div><!-- /.tab-pane -->
        </div>
      </aside><!-- /.control-sidebar -->
      <!-- Add the sidebar's background. This div must be placed
           immediately after the control sidebar -->
      <div class="control-sidebar-bg"></div>
    </div><!-- ./wrapper -->

proj_compras/templates/nav.html
  <meta charset="UTF-8">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<div class="wrapper">
      <header class="main-header">
        <!-- Logo -->
        <a href="#" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini">Proy</span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg">Proyecto</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">

              <!-- User Account: style can be found in dropdown.less -->
               <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <span class="hidden-xs">{{ user.first_name|capfirst }} {{ user.last_name|capfirst }}</span>
                </a>
                <ul class="dropdown-menu">
                  <!-- User image -->
                 <li class="user-header">
                     <p>
                       {{ user.first_name|capfirst }} {{ user.last_name|capfirst }}
                    </p>
                  </li>
                  <!-- Menu Footer-->
                  <li class="user-footer">
                    <div class="pull-left">
                      <!--<a href="#" class="btn btn-default btn-flat">Profile</a>-->
                    </div>
                    <div class="pull-right">
                      <a href="{% url 'usuarios:logout' %}" class="btn btn-default btn-flat">Salir</a>
                    </div>
                  </li>
                </ul>
              </li>
              <!-- Control Sidebar Toggle Button -->
              <!--<li>
                <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
              </li>-->
            </ul>
          </div>
        </nav>
      </header>
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- Sidebar user panel -->
        <!--  <div class="user-panel">
            <div class="pull-left image">
            <img src="{{ MEDIA_URL }}{{ user.avatar }}" class="img-circle" alt="User Image" >
            </div>
            <div class="pull-left info">
              <p>{{ user.username|capfirst }} {{ user.last_name|capfirst }}</p>
              <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
          </div> -->

          <!-- sidebar menu: : style can be found in sidebar.less -->
          <ul class="sidebar-menu">
            <li class="header">NAVEGACION</li>



            <li class="treeview">
              <a href="#">
                <i class="fa fa-truck"></i> <span>Proveedores</span> <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li class="active"><a href="{% url 'proveedores:lista' %}"><i class="fa fa-check-square"></i> Lista</a></li>
                {% if perms.proveedores.can_add %}
                <li><a href="{% url 'proveedores:nuevo' %}"><i class="fa fa-save"></i><small class="label pull-right bg-green">Nuevo</small>Nuevo</a></li>
                {% endif %}
              </ul>
            </li>

            <li class="treeview">
              <a href="#">
                <i class="fa fa-tag"></i> <span>Mercaderias</span> <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li class="active"><a href="{% url 'mercaderias:lista' %}"><i class="fa fa-check-square"></i> Lista</a></li>
                <li class="active"><a href="{% url 'mercaderias:lista_categorias' %}"><i class="fa fa-tags"></i> Categorias</a></li>
              </ul>
            </li>

            <li class="treeview">
              <a href="#">
                <i class="fa fa-shopping-cart"></i> <span>Compras</span> <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li class="active"><a href="{% url 'compras:lista_solicitudes' %}"><i class="fa fa-check-square"></i> Solicitudes</a></li>
                <li class="active"><a href="{% url 'compras:lista_cotizaciones' %}"><i class="fa fa-usd"></i> Cotizaciones</a></li>
                <li class="active"><a href="{% url 'compras:lista_ordenes' %}"><i class="fa fa-credit-card"></i> Ordenes de Compra</a></li>
                <li class="active"><a href="{% url 'compras:lista_facturas' %}"><i class="fa fa-file-text-o"></i> Facturas</a></li>
              </ul>
            </li>

        <!--    <li class="header">Alertas</li>
            <li><a href="#"><i class="fa fa-circle-o text-red"></i> <span>Medicamentos</span></a></li>
            <li><a href="#"><i class="fa fa-circle-o text-yellow"></i> <span>Compras</span></a></li>
            <li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Ventas</span></a></li>      -->
        </section>
        <!-- /.sidebar -->
      </aside>