compras/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = [

    url(regex=r'^solicitudes/$',
        view=views.SolicitudDeCompraList.as_view(),
        name='lista_solicitudes'
        ),

    url(regex=r'^solicitudes/nueva$',
        view=views.solicitud_de_compra_cru,
        name='nueva_solicitud'
        ),

    url(regex=r'^solicitudes/(?P<pk>[\w-]+)/editar/$',
        view=views.solicitud_de_compra_cru,
        name='editar_solicitud'
        ),

    url(regex=r'^solicitudes/(?P<pk>[\w-]+)/$',
        view=views.detalle_solicitud_de_compra,
        name='detalle_solicitud'
        ),

    url(regex=r'^solicitudes/(?P<pk>[\w-]+)/borrar/$',
        view=views.BorrarSolicitudDeCompra.as_view(),
        name='borrar_solicitud'
        ),

    url(regex=r'^solicitudes/(?P<pk>[\w-]+)/aprobar/$',
        view=views.AprobarSolicitudDeCompra.as_view(),
        name='aprobar_solicitud'
        ),

    url(regex=r'^cotizaciones/$',
        view=views.CotizacionesList.as_view(),
        name='lista_cotizaciones'
        ),

    url(regex=r'^cotizaciones/nueva/$',
        view=views.cotizacion_cru,
        name='nueva_cotizacion'
        ),

    url(regex=r'^cotizaciones/(?P<pk>[\w-]+)/editar/$',
        view=views.cotizacion_cru,
        name='editar_cotizacion'
        ),

    url(regex=r'^cotizaciones/(?P<pk>[\w-]+)/$',
        view=views.detalle_cotizacion,
        name='detalle_cotizacion'
        ),

    url(regex=r'^cotizaciones/(?P<pk>[\w-]+)/borrar/$',
        view=views.BorrarCotizacion.as_view(),
        name='borrar_cotizacion'
        ),

    url(regex=r'^cotizaciones/(?P<pk>[\w-]+)/aprobar/$',
        view=views.AprobarCotizacion.as_view(),
        name='aprobar_cotizacion'
        ),

    url(regex=r'^cotizaciones/(?P<pk>[\w-]+)/rechazar/$',
        view=views.RechazarCotizacion.as_view(),
        name='rechazar_cotizacion'
        ),

    url(regex=r'^ordenes/$',
        view=views.OrdenesList.as_view(),
        name='lista_ordenes'
        ),

    url(regex=r'^ordenes/nueva/$',
        view=views.orden_de_compra_cru,
        name='nueva_orden'
        ),

    url(regex=r'^ordenes/(?P<pk>[\w-]+)/$',
        view=views.detalle_orden,
        name='detalle_orden'
        ),

    url(regex=r'^ordenes/(?P<pk>[\w-]+)/editar/$',
        view=views.orden_de_compra_cru,
        name='editar_orden'
        ),

    url(regex=r'^ordenes/(?P<pk>[\w-]+)/borrar/$',
        view=views.BorrarOrdenDeCompra.as_view(),
        name='borrar_orden'
        ),

    url(regex=r'^facturas/$',
        view=views.FacturasList.as_view(),
        name='lista_facturas'
        ),

    url(regex=r'^facturas/nueva/$',
        view=views.CrearFactura.as_view(),
        name='nueva_factura'
        ),

    url(regex=r'^facturas/(?P<pk>[\w-]+)/$',
        view=views.DetalleFactura.as_view(),
        name='detalle_factura'
        ),

    url(regex=r'^facturas/(?P<pk>[\w-]+)/editar/$',
        view=views.ActualizarFactura.as_view(),
        name='editar_factura'
        ),

    url(regex=r'^facturas/(?P<pk>[\w-]+)/borrar/$',
        view=views.BorrarFactura.as_view(),
        name='borrar_factura'
        ),
]

contactos/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = [

    url(regex=r'^nuevo/$',
        view=views.contacto_cru,
        name='nuevo'
        ),

    url(regex=r'^(?P<uuid>[\w-]+)/editar/$',
        view=views.contacto_cru,
        name='editar'
        ),

    url(regex=r'^(?P<pk>[\w-]+)/borrar/$',
        view=views.BorrarContacto.as_view(),
        name='borrar'
        ),

    url(regex=r'^(?P<uuid>[\w-]+)/$',
        view=views.detalle_contacto,
        name='detalle'
        ),

]

proj_compras/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings


admin.autodiscover()


urlpatterns = patterns(
    '',

    url(r'^admin/', include(admin.site.urls)),

    #login-users
    url(r'^',
        include('usuarios.urls',  namespace='usuarios')
        ),

    # Login/Logout URLs
    #(r'^login/$',
    #    'django.contrib.auth.views.login', {'template_name': 'login.html'}
    #),

    #(r'^logout/$',
    #    'django.contrib.auth.views.logout', {'next_page': '/login/'}
    #),

    url(r'^proveedores/',
        include('proveedores.urls', namespace='proveedores')
        ),

    url(r'^contactos/',
        include('contactos.urls', namespace='contactos')
        ),

    url(r'^mercaderias/',
        include('mercaderias.urls', namespace='mercaderias')
        ),

    url(r'^compras/',
        include('compras.urls', namespace='compras')
        ),
)
#Added for debug toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

contactos/models.py
from django.db import models

from shortuuidfield import ShortUUIDField

from proveedores.models import Proveedor


# Create your models here.
class Contacto(models.Model):
    uuid = ShortUUIDField(unique=True)
    proveedor = models.ForeignKey(Proveedor,
                                  on_delete=models.CASCADE,
                                  blank=True,
                                  null=True
                                  )
    nombre = models.CharField(max_length=80)
    email = models.EmailField(blank=True)
    #FIXME Cantidad dinamica de telofonos?
    telefono = models.CharField(max_length=40, blank=True)
    #telefono_2 = models.CharField(max_length=40, blank=True)
    direccion = models.CharField(max_length=80, blank=True)
    #FIXME Se podria agregar una tabla direccion con ciudad, provincia, etc
    #direccion_2 = models.CharField(max_length=80, blank=True)
    pagina_web = models.URLField(blank=True)
    detalles = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = 'contactos'

    def __str__(self):
        return "%s" % self.nombre

    @models.permalink
    def get_absolute_url(self):
        return 'contactos:detalle', [self.uuid]

    @models.permalink
    def get_update_url(self):
        return 'contactos:editar', [self.uuid]

    @models.permalink
    def get_delete_url(self):
        return 'contactos:borrar', [self.id]

contactos/forms.py
from django import forms

from .models import Contacto


class ContactoForm(forms.ModelForm):
    class Meta:
        model = Contacto
        fields = ('nombre', 'email', 'telefono', 'direccion',
                  'pagina_web', 'detalles', 'proveedor')
        widgets = {
            'nombre': forms.TextInput(
                attrs={'placeholder': 'Nombre', 'class': 'form-control'}
            ),
            'email': forms.TextInput(
                attrs={'placeholder': 'Email', 'class': 'form-control'}
            ),
            'telefono': forms.TextInput(
                attrs={'placeholder': 'Telefono', 'class': 'form-control'}
            ),
            'direccion': forms.TextInput(
                attrs={'placeholder': 'Direccion', 'class': 'form-control'}
            ),
            'pagina_web': forms.TextInput(
                attrs={'placeholder': 'Direccion Web', 'class': 'form-control'}
            ),
            'detalles': forms.Textarea(
                attrs={'placeholder': 'Detalles', 'class': 'form-control'}
            ),
        }

contactos/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,  HttpResponseForbidden, Http404
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from django.views.generic.edit import DeleteView
from braces.views import LoginRequiredMixin, PermissionRequiredMixin

from .models import Contacto
from .forms import ContactoForm
from proveedores.models import Proveedor


@login_required()
def detalle_contacto(request, uuid):

    contacto = Contacto.objects.get(uuid=uuid)

    template = 'contactos/detalle_contacto.html'

    variables = {
        'contacto': contacto,
    }

    return render(request, template, variables)


@login_required()
def contacto_cru(request, uuid=None, proveedor=None):

    if uuid:  # Si hay uuid estoy editando
        if not request.user.has_perm('contactos.can_edit'):
                    return HttpResponseForbidden()
        contacto = get_object_or_404(Contacto, uuid=uuid)
    else:
        if not request.user.has_perm('contactos.can_edit'):
            return HttpResponseForbidden()
        contacto = Contacto()

    if request.POST:
        form = ContactoForm(request.POST, instance=contacto)
        if form.is_valid():
            proveedor = form.cleaned_data['proveedor']
            # save the data
            contacto = form.save()
            if request.is_ajax():
                return render(request,
                              'contactos/item_contacto.html',
                              {'proveedor': proveedor, 'contacto': contacto})
            else:
                reverse_url = reverse(
                    'proveedores:detalle',
                    args=(proveedor.uuid,)
                )
                return HttpResponseRedirect(reverse_url)
        else:
            # if the form isn't valid, still fetch the
            # account so it can be passed to the template
            proveedor = form.cleaned_data['proveedor']
    else:
        form = ContactoForm(instance=contacto)

    # this is used to fetch the account if it exists as a URL parameter
    if request.GET.get('proveedor', ''):
        proveedor = Proveedor.objects.get(id=request.GET.get('proveedor', ''))

    variables = {
        'form': form,
        'contacto': contacto,
        'proveedor': proveedor,
    }

    if request.is_ajax():
        template = 'contactos/item_contacto_form.html'
    else:
        template = 'contactos/contacto_cru.html'

    return render(request, template, variables)


#Create Mixin to subclass with Deleteview
class ContactoMixin(object):
    model = Contacto

    def get_context_data(self, **kwargs):
        kwargs.update({'object_name': 'Contacto'})
        return kwargs

    def dispatch(self, *args, **kwargs):
        return super(ContactoMixin, self).dispatch(*args, **kwargs)


class BorrarContacto(LoginRequiredMixin, PermissionRequiredMixin, ContactoMixin, DeleteView):
    template_name = 'contactos/eliminar_contacto.html'
    permission_required = 'contactos.can_delete'
    raise_exception = True

    def get_object(self, queryset=None):
        obj = super(BorrarContacto, self).get_object()
        proveedor = Proveedor.objects.get(id=obj.proveedor.id)
        self.proveedor = proveedor
        return obj

    def get_success_url(self):
        return reverse(
            'proveedores:detalle',
            args=(self.proveedor.uuid,)
        )

proj_compras/templates/contactos/contacto_cru.html
{% extends 'base.html' %}
{% block title %}Operaciones con Contactos{% endblock title %}

{% block content %}
    <div id="content-container" class="container p-none">
        <h4 class="ad-mh">Agregar Contacto</h4>
        {% include 'contactos/item_contacto_form.html' %}
    </div>
{% endblock content %}

proj_compras/templates/contactos/detalle_contacto.html
{% extends 'base.html' %}
{% block title %}Detalles de Contacto{% endblock title %}

{% block content %}
    <div id="content-container" class="container p-none">
        <div id="cd-body" class="row">
            <h4 class="ad-mh">Detalle de Contacto</h4>
            <table id="cd-table" class="table">
                <tbody>
                    {% include 'contacts/item_contacto.html' %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock content %}

proj_compras/templates/contactos/eliminar_contacto.html
{% extends "proveedores/base_proveedores_lista.html" %}
{% block title %}Eliminar Contacto{% endblock title %}
{% block content %}
{% include "nav.html" %}
{% block producto %}
<div class="wrapper">
      <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
        <!-- Main content -->
    <section class="content">
      <!-- START ALERTS AND CALLOUTS -->
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">
            <div class="box-header with-border">
              <i class="fa fa-bullhorn"></i>
            </div><!-- /.box-header -->
              <div class="box-body">
                  <div class="callout callout-danger">
                    <h1> Eliminar</h1>
                    <form method="POST">
                    {% csrf_token %}
                      <p class="coloreliminar">¿Desea eliminar al contcato "{{ object.nombre }}?</p>
                      <input type="submit" value="Sí" class="btn btn-warning">
                      <input class="btn btn-info" type="button" value="No" onclick="window.history.go(-1);"/>
                    </form>
                  </div>
              </div><!-- /.box -->
          </div><!-- /.col -->
        </div><!-- /.row -->
    </section><!-- /.content -->
  </div><!-- /.content-wrapper -->

{% include "footer.html" %}
 {% endblock producto %}
{% endblock content %}

proj_compras/templates/contactos/item_contacto.html
<tr>
    <td> {{ contacto.nombre }}</td>
    <td> {{ contacto.telefono }} </td>
    <td> {{ contacto.email }} </td>
    <td> {{ contacto.direccion }} </td>
    <td> {{ contacto.pagina_web }} </td>
    <td class="text-left">
       <!--- {% if user.is_authenticated %}
        <a href="{{ contacto.get_absolute_url }} " class="btn btn-success"><span class="glyphicon glyphicon-eye-open"></span></a>
        {% endif %} -->
        {% if perms.contactos.change_contacto %}
        <a href="{{ contacto.get_update_url }}?proveedor={{ proveedor.id }}" id="editar-contacto" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span></a>
        {% endif %}
        {% if perms.contactos.delete_contacto %}
        <a href="{{ contacto.get_delete_url }}" id="borrar-contacto" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a>
        {% endif %}
    </td>
</tr>

proj_compras/templates/contactos/item_contacto_form.html
<form id="contact-form"
      {# POST Destination #}
      action="{% if contacto.uuid %}
      {% url 'contactos:editar' contacto.uuid %}
      {% else %} {% url 'contactos:nuevo' %}
      {% endif %}"
      method="post">
    {% csrf_token %}
    <table class="table">
        <tbody>
            <tr>
                <td class="p-l-none">{{ form.nombre }}</td>
                <td>{{ form.telefono }}</td>
                <td>{{ form.email }}</td>
                <td>{{ form.direccion }}</td>
                <td class="p-r-none">{{ form.pagina_web }}</td>
            </tr>
            {% if form.errors %}
                <tr>
                    <td>{{ form.nombre.errors }}</td>
                    <td>{{ form.email.errors }}</td>
                    <td>{{ form.telefono.errors }}</td>
                    <td>{{ form.direccion.errors }}</td>
                    <td>{{ form.pagina_web.errors }}</td>
                </tr>
            {% endif %}
        </tbody>
    </table>
    <input id="id_proveedor" name="proveedor"
           type="hidden"
           value="{% if request.GET.proveedor %}
           {{ request.GET.proveedor }}{% else %}{{ proveedor.id }}{% endif %}"/>
    <input id="contact-submit" class="btn btn-block btn-success" type="submit" value="GUARDAR"/>
</form>