compras/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = [

    url(regex=r'^solicitudes/$',
        view=views.SolicitudDeCompraList.as_view(),
        name='lista_solicitudes'
        ),

    url(regex=r'^solicitudes/nueva$',
        view=views.solicitud_de_compra_cru,
        name='nueva_solicitud'
        ),

    url(regex=r'^solicitudes/(?P<pk>[\w-]+)/editar/$',
        view=views.solicitud_de_compra_cru,
        name='editar_solicitud'
        ),

    url(regex=r'^solicitudes/(?P<pk>[\w-]+)/$',
        view=views.detalle_solicitud_de_compra,
        name='detalle_solicitud'
        ),

    url(regex=r'^solicitudes/(?P<pk>[\w-]+)/borrar/$',
        view=views.BorrarSolicitudDeCompra.as_view(),
        name='borrar_solicitud'
        ),

    url(regex=r'^solicitudes/(?P<pk>[\w-]+)/aprobar/$',
        view=views.AprobarSolicitudDeCompra.as_view(),
        name='aprobar_solicitud'
        ),

    url(regex=r'^cotizaciones/$',
        view=views.CotizacionesList.as_view(),
        name='lista_cotizaciones'
        ),

    url(regex=r'^cotizaciones/nueva/$',
        view=views.cotizacion_cru,
        name='nueva_cotizacion'
        ),

    url(regex=r'^cotizaciones/(?P<pk>[\w-]+)/editar/$',
        view=views.cotizacion_cru,
        name='editar_cotizacion'
        ),

    url(regex=r'^cotizaciones/(?P<pk>[\w-]+)/$',
        view=views.detalle_cotizacion,
        name='detalle_cotizacion'
        ),

    url(regex=r'^cotizaciones/(?P<pk>[\w-]+)/borrar/$',
        view=views.BorrarCotizacion.as_view(),
        name='borrar_cotizacion'
        ),

    url(regex=r'^cotizaciones/(?P<pk>[\w-]+)/aprobar/$',
        view=views.AprobarCotizacion.as_view(),
        name='aprobar_cotizacion'
        ),

    url(regex=r'^cotizaciones/(?P<pk>[\w-]+)/rechazar/$',
        view=views.RechazarCotizacion.as_view(),
        name='rechazar_cotizacion'
        ),

    url(regex=r'^ordenes/$',
        view=views.OrdenesList.as_view(),
        name='lista_ordenes'
        ),

    url(regex=r'^ordenes/nueva/$',
        view=views.orden_de_compra_cru,
        name='nueva_orden'
        ),

    url(regex=r'^ordenes/(?P<pk>[\w-]+)/$',
        view=views.detalle_orden,
        name='detalle_orden'
        ),

    url(regex=r'^ordenes/(?P<pk>[\w-]+)/editar/$',
        view=views.orden_de_compra_cru,
        name='editar_orden'
        ),

    url(regex=r'^ordenes/(?P<pk>[\w-]+)/borrar/$',
        view=views.BorrarOrdenDeCompra.as_view(),
        name='borrar_orden'
        ),

    url(regex=r'^facturas/$',
        view=views.FacturasList.as_view(),
        name='lista_facturas'
        ),

    url(regex=r'^facturas/nueva/$',
        view=views.CrearFactura.as_view(),
        name='nueva_factura'
        ),

    url(regex=r'^facturas/(?P<pk>[\w-]+)/$',
        view=views.DetalleFactura.as_view(),
        name='detalle_factura'
        ),

    url(regex=r'^facturas/(?P<pk>[\w-]+)/editar/$',
        view=views.ActualizarFactura.as_view(),
        name='editar_factura'
        ),

    url(regex=r'^facturas/(?P<pk>[\w-]+)/borrar/$',
        view=views.BorrarFactura.as_view(),
        name='borrar_factura'
        ),
]

proj_compras/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings


admin.autodiscover()


urlpatterns = patterns(
    '',

    url(r'^admin/', include(admin.site.urls)),

    #login-users
    url(r'^',
        include('usuarios.urls',  namespace='usuarios')
        ),

    # Login/Logout URLs
    #(r'^login/$',
    #    'django.contrib.auth.views.login', {'template_name': 'login.html'}
    #),

    #(r'^logout/$',
    #    'django.contrib.auth.views.logout', {'next_page': '/login/'}
    #),

    url(r'^proveedores/',
        include('proveedores.urls', namespace='proveedores')
        ),

    url(r'^contactos/',
        include('contactos.urls', namespace='contactos')
        ),

    url(r'^mercaderias/',
        include('mercaderias.urls', namespace='mercaderias')
        ),

    url(r'^compras/',
        include('compras.urls', namespace='compras')
        ),
)
#Added for debug toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

compras/models.py
from django.db import models
from django.conf import settings
from django.utils.timezone import now
from decimal import Decimal

from mercaderias.models import Mercaderia
from proveedores.models import Proveedor
from proj_compras.constants import ESTADO_SOLICITUD_CHOICES, SOLICITUD_PENDIENTE
from proj_compras.constants import ESTADO_COTIZACION_CHOICES, COTIZACION_PENDIENTE
from proj_compras.constants import ESTADO_PAGO_CHOICES, PAGO_PENDIENTE
from proj_compras.constants import FORMA_DE_PAGO_CHOICES, CONTADO
from proj_compras.constants import TIPO_FACTURA_CHOICES, FACTURA_A


# Create your models here.
class SolicitudDeCompra(models.Model):

    estado = models.CharField(max_length=5,
                              choices=ESTADO_SOLICITUD_CHOICES,
                              default=SOLICITUD_PENDIENTE)
    fecha_generada = models.DateTimeField(auto_now_add=True)
    fecha_ultima_modificacion = models.DateTimeField(auto_now=True)
    generada_por = models.ForeignKey(settings.AUTH_USER_MODEL,
                                     on_delete=models.SET_NULL,
                                     blank=True,
                                     null=True,
                                     related_name='generada_por')
    aprobada_por = models.ForeignKey(settings.AUTH_USER_MODEL,
                                     on_delete=models.SET_NULL,
                                     blank=True,
                                     null=True,
                                     related_name='aprobada_por')
    observaciones = models.TextField(blank=True,
                                     null=True)

    class Meta:
        verbose_name = "SolicitudDeCompra"
        verbose_name_plural = "SolicitudesDeCompra"
        permissions = (
            ("puede_aprobar_solicitud",
             "Puede aprobar las solicitudes pendientes"),
        )

    def __str__(self):
        return "SolicitudDeCompra:%s" % self.id

    @models.permalink
    def get_absolute_url(self):
        return 'compras:detalle_solicitud', [self.id]

    @models.permalink
    def get_update_url(self):
        return 'compras:editar_solicitud', [self.id]

    @models.permalink
    def get_delete_url(self):
        return 'compras:borrar_solicitud', [self.id]

    @models.permalink
    def get_aprobar_url(self):
        return 'compras:aprobar_solicitud', [self.id]


class DetalleSolicitud(models.Model):
    cantidad = models.PositiveIntegerField()
    mercaderia = models.ForeignKey(Mercaderia)
    solicitud = models.ForeignKey(SolicitudDeCompra,
                                  on_delete=models.CASCADE)

    class Meta:
        verbose_name = "DetalleSolicitud"
        verbose_name_plural = "DetallesSolicitud"

    def __str__(self):
        return "DetalleSolicitud:%s" % self.id


class Cotizacion(models.Model):
    fecha_generada = models.DateTimeField(auto_now_add=True)
    estado = models.CharField(max_length=5,
                              choices=ESTADO_COTIZACION_CHOICES,
                              default=COTIZACION_PENDIENTE)
    modificado_por = models.ForeignKey(settings.AUTH_USER_MODEL,
                                       on_delete=models.SET_NULL,
                                       blank=True,
                                       null=True,
                                       related_name='modificado_por')
    proveedor = models.ForeignKey(Proveedor,
                                  on_delete=models.SET_NULL,
                                  null=True,
                                  blank=True)
    solicitud = models.ForeignKey(SolicitudDeCompra,
                                  on_delete=models.CASCADE,
                                  null=True,
                                  blank=True)
    descuento = models.PositiveIntegerField(blank=True, null=True, default=0)
    iva = models.PositiveIntegerField(default=21)

    def get_subtotal(self):
        detalles = DetalleCotizacion.objects.filter(cotizacion=self)
        total = 0
        for d in detalles:
            total = total + d.get_subtotal()

        return total

    def get_calculo_iva(self):
        return round(self.get_subtotal() * Decimal(
            (1.0 - self.descuento / 100.0) * (self.iva / 100.0)), 2)

    def get_calculo_descuento(self):
        return round(self.get_subtotal() * Decimal(self.descuento / 100.0), 2)

    def get_total(self):
        return round(self.get_subtotal() * Decimal(
            (1.0 - self.descuento / 100.0) * (1.0 + self.iva / 100.0)), 2)

    class Meta:
        verbose_name = "Cotizacion"
        verbose_name_plural = "Cotizaciones"
        permissions = (
            ("puede_aprobar_orden_de_compra",
             "Puede aprobar las cotizaciones pendientes"),
        )

    @models.permalink
    def get_absolute_url(self):
        return 'compras:detalle_cotizacion', [self.id]

    @models.permalink
    def get_update_url(self):
        return 'compras:editar_cotizacion', [self.id]

    @models.permalink
    def get_delete_url(self):
        return 'compras:borrar_cotizacion', [self.id]

    @models.permalink
    def get_aprobar_url(self):
        return 'compras:aprobar_cotizacion', [self.id]

    @models.permalink
    def get_rechazar_url(self):
        return 'compras:rechazar_cotizacion', [self.id]

    def __str__(self):
        return "Cotizacion: %s" % self.id


class DetalleCotizacion(models.Model):
    cantidad = models.PositiveIntegerField()
    mercaderia = models.ForeignKey(Mercaderia)
    precio = models.DecimalField(max_digits=15, decimal_places=2)
    cotizacion = models.ForeignKey(Cotizacion,
                                   on_delete=models.CASCADE)

    def get_subtotal(self):
        return self.cantidad * self.precio

    class Meta:
        verbose_name = "DetalleCotizacion"
        verbose_name_plural = "DetallesCotizacion"

    def __str__(self):
        return "%s" % self.id


class OrdenDeCompra(models.Model):
    numero = models.PositiveIntegerField(unique=True, default=0)
    cotizacion = models.ForeignKey(Cotizacion)
    forma_de_pago = models.CharField(
        max_length=5,
        choices=FORMA_DE_PAGO_CHOICES,
        null=True  # Fixme cambiar por blank
    )
    cuotas = models.PositiveIntegerField(blank=True, default=1)
    #fecha_generada
    #fecha_ultima_modificacion
    #fecha_de_entrega

    class Meta:
        verbose_name = "OrdenDeCompra"
        verbose_name_plural = "OrdenesDeCompra"

    def __str__(self):
        return "Orden de Compra nro: %s" % self.numero

    def get_subtotal(self):
        return self.cotizacion.get_subtotal()

    def get_calculo_iva(self):
        return self.cotizacion.get_calculo_iva()

    def get_calculo_descuento(self):
        return self.cotizacion.get_calculo_descuento()

    def get_total(self):
        return self.cotizacion.get_total()

    @models.permalink
    def get_absolute_url(self):
        return 'compras:detalle_orden', [self.id]

    @models.permalink
    def get_update_url(self):
        return 'compras:editar_orden', [self.id]

    @models.permalink
    def get_delete_url(self):
        return 'compras:borrar_orden', [self.id]


class FacturaDeCompra(models.Model):
    numero = models.PositiveIntegerField()
    fecha = models.DateField(blank=True)
    importe = models.DecimalField(max_digits=15, decimal_places=2)
    foto = models.ImageField(upload_to='facturas_de_compra', blank=True)
    tipo = models.CharField(
        max_length=5,
        choices=TIPO_FACTURA_CHOICES,
        default=FACTURA_A
    )
    orden = models.OneToOneField(
        OrdenDeCompra,
        on_delete=models.CASCADE,
        null=True
    )

    class Meta:
        verbose_name = "FacturaDeCompra"
        verbose_name_plural = "FacturasDeCompra"

    def __str__(self):
        return "Factura nro: %s" % self.numero

    def get_proveedor(self):
        return self.orden.cotizacion.proveedor

    def get_detalles(self):
        detalles = DetalleCotizacion.objects.filter(
            cotizacion=self.orden.cotizacion
        )
        return detalles

    def get_subtotal(self):
        return self.orden.get_subtotal()

    def get_calculo_iva(self):
        return self.orden.get_calculo_iva()

    def get_calculo_descuento(self):
        return self.orden.get_calculo_descuento()

    def get_total(self):
        return self.orden.get_total()

    @models.permalink
    def get_absolute_url(self):
        return 'compras:detalle_factura', [self.id]

    @models.permalink
    def get_update_url(self):
        return 'compras:editar_factura', [self.id]

    @models.permalink
    def get_delete_url(self):
        return 'compras:borrar_factura', [self.id]


#class DetalleOrdenCompra(models.Model):
#    cantidad = models.PositiveIntegerField()
#    mercaderia = models.ForeignKey(Mercaderia)
#    precio = models.DecimalField(max_digits=15, decimal_places=3)
#    orden = models.ForeignKey(Cotizacion,
#                              on_delete=models.CASCADE)
#
#    def get_subtotal(self):
#        return self.cantidad * self.precio
#
#    class Meta:
#        verbose_name = "DetalleOrdenDeCompra"
#        verbose_name_plural = "DetallesOrdenDeCompra"
#
#    def __str__(self):
#        pass


class PagoDeCompra(models.Model):
    fecha_de_pago = models.DateField(blank=True, null=True)
    orden = models.ForeignKey(OrdenDeCompra)
    importe = models.DecimalField(max_digits=15, decimal_places=2)
    estado = models.CharField(max_length=5,
                              choices=ESTADO_PAGO_CHOICES,
                              null=True,
                              blank=True,
                              default=PAGO_PENDIENTE)
    foto = models.ImageField(upload_to='comprobantes_de_pago', blank=True)

    class Meta:
        verbose_name = "PagoDeCompra"
        verbose_name_plural = "PagosDeCompra"

    def __str__(self):
        return "PagosDeCompra:%s" % self.id

proj_compras/templates/compras/cotizaciones_lista.html
{% extends "compras/base_compras.html" %}
{% block title %}Compras | Cotizaciones{% endblock title %}
{% block content %}
{% include "nav.html" %}
{% block producto %}
    <div class="wrapper">
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Cotizaciones
          </h1>
          <ol class="breadcrumb">
            <li><a href=""><i class="fa fa-dashboard"></i>Inicio</a></li>
            <li class="active">Cotizaciones</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-xs-12">

                <div class="box box-primary">
                  <div class="box-header with-border">
                    <!---
                    {% if perms.compras.add_solicituddecompra %}
                    <h3 class="box-title"><a href="{% url 'compras:nueva_solicitud' %}" class="btn btn-success">
                      Nueva Solicitud
                    </a></h3>
                    {% endif %}
                    -->
                    <div class="box-tools pull-right">
                      <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div><!-- /.box-tools -->
                  </div><!-- /.box-header -->
                  <div class="box-body">
                  <table id="example1" class="table table-bordered table-striped">
                    <thead>
                     <tr>
                        <th>N°</th>
                        <th>Fecha Generada</th>
                        <th>Estado</th>
                        <th>Proveedor</th>
                        <th>Acciones</th>
                      </tr>
                    </thead>
                    <tbody>

                     {% for cotizacion in cotizaciones %}

                        <tr>
                          <td>{{ forloop.counter}}</td>
                          <td>{{ cotizacion.fecha_generada }} </td>
                          <td>{{ cotizacion.get_estado_display }}</td>
                          <td>{{ cotizacion.proveedor }}</td>
                          <td class="text-right">
                                  {% if user.is_authenticated %}
                                  <a href="{{ cotizacion.get_absolute_url }}" class="btn btn-success"><span class="glyphicon glyphicon-eye-open"></span></a>
                                  {% endif %}
                                  {% if perms.compras.change_cotizacion %}
                                  <a href="{{ cotizacion.get_update_url }}" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span></a>
                                  {% endif %}
                                  {% if perms.compras.delete_cotizacion %}
                                  <a href="{{ cotizacion.get_delete_url }}" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a>
                                  {% endif %}
                                  {% if cotizacion.estado == "A" %}
                                  <a href="{% url 'compras:nueva_orden' %}?cotizacion={{cotizacion.id}}" class="btn btn-info"><span class="glyphicon glyphicon-credit-card"></span></a>
                                  {% endif %}
                            </td>

                          </tr>
                      {% endfor %}
                    </tbody>

                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->
      <footer class="main-footer">
{% include "footer.html" %}
 {% endblock producto %}
{% endblock content %}

proj_compras/templates/compras/detalle_factura.html
{% extends "compras/base_compras.html" %}
{% block title %}Compras | Detalle Factura de Compra{% endblock title %}
{% block content %}
{% include "nav.html" %}
{% block producto %}
<div class="wrapper">
      <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
        <!-- Main content -->
    <section class="content">
      <!-- START ALERTS AND CALLOUTS -->
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">

            <div class="box-header with-border">
                <a href="{% url 'compras:lista_facturas'%}" class="btn btn-success">
                    <span class="glyphicon glyphicon-chevron-left"></span> Regresar
                </a>
                    <div class="box-tools pull-right">
                      <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div><!-- /.box-tools -->
            </div><!-- /.box-header -->
              <div class="box-body">
                  <div class="section">
                        <table class="table table-striped table table-hover ">
                            <tbody>
                                <tr class="success">
                                      <td><strong>Numero:</strong></td>
                                      <td>{{ factura.numero }} </td>
                                </tr>
                                <tr class="success">
                                      <td><strong>Fecha:</strong></td>
                                      <td>{{ factura.fecha }} </td>
                                </tr>
                                <tr class="success">
                                   <td><strong>Tipo:</strong></td>
                                   <td>{{ factura.get_tipo_display }}</td>
                                </tr>
                                <tr class="success">
                                   <td><strong>Proveedor:</strong></td>
                                   <td>{{ factura.get_proveedor }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div> <!-- section -->
                    <div class="panel-body">
                        <h3 class="page-header"> Detalle </h2>
                        <table class="table-striped table table-hover">
                            <thead>
                                <tr>
                                    <th scope="col"> Cantidad </th>
                                    <th scope="col"> Descripción </th>
                                    <th scope="col"> Precio Unitario </th>
                                    <th scope="col"> Subtotal </th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for detalle in factura.get_detalles %}
                                    <tr>
                                        <td> {{ detalle.cantidad }} </td>
                                        <td> {{ detalle.mercaderia }} </td>
                                        <td> {{ detalle.precio }} </td>
                                        <td> {{ detalle.get_subtotal }} </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        <div class="col-xs-6">
                        </div>
                        <div class="col-xs-6">
                            <div class="lead"> Totales de la compra </div>
                            <div class"table-responsive">
                                <table class="table">
                                    <tbody>
                                        <tr>
                                            <th style="width:50%">Subtotal:</th>
                                            <td align="center"> {{ factura.get_subtotal }}</td>
                                        </tr>
                                        <tr>
                                            <th style="width:50%">Descuento({{ factura.orden.cotizacion.descuento }}%):</th>
                                            <td align="center"> {{ factura.get_calculo_descuento }}</td>
                                        </tr>
                                        <tr>
                                            <th style="width:50%">IVA({{factura.orden.cotizacion.iva}}%):</th>
                                            <td align="center"> {{ factura.get_calculo_iva }}</td>
                                        </tr>
                                        <tr>
                                            <th style="width:50%">Total: $:</th>
                                            <td align="center"> {{ factura.get_total }}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div> <!-- panel-body -->

              </div><!-- /.box -->
          </div><!-- /.col -->
        </div><!-- /.row -->
    </section><!-- /.content -->
  </div><!-- /.content-wrapper -->

{% include "footer.html" %}
{% endblock producto %}
{% endblock content %}

proj_compras/templates/compras/facturas_lista.html
{% extends "compras/base_compras.html" %}
{% block title %}Compras | Facturas{% endblock title %}
{% block content %}
{% include "nav.html" %}
{% block producto %}
    <div class="wrapper">
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Facturas
          </h1>
          <ol class="breadcrumb">
            <li><a href=""><i class="fa fa-dashboard"></i>Inicio</a></li>
            <li class="active">Facturas</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-xs-12">

                <div class="box box-primary">
                  <div class="box-header with-border">
                    <!---
                    {% if perms.compras.add_solicituddecompra %}
                    <h3 class="box-title"><a href="{% url 'compras:nueva_solicitud' %}" class="btn btn-success">
                      Nueva Solicitud
                    </a></h3>
                    {% endif %}
                    -->
                    <div class="box-tools pull-right">
                      <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div><!-- /.box-tools -->
                  </div><!-- /.box-header -->
                  <div class="box-body">
                  <table id="example1" class="table table-bordered table-striped">
                    <thead>
                     <tr>
                        <th>N°</th>
                        <th>Proveedor</th>
                        <th>Fecha</th>
                        <th>Tipo</th>
                        <th>Importe</th>
                        <th>Acciones</th>
                      </tr>
                    </thead>
                    <tbody>

                     {% for factura in facturas %}

                        <tr>
                          <td>{{ factura.numero }}</td>
                          <td>{{ factura.get_proveedor }} </td>
                          <td>{{ factura.fecha }}</td>
                          <td>{{ factura.get_tipo_display }}</td>
                          <td>{{ factura.importe }}</td>
                          <td class="text-right">
                                  {% if user.is_authenticated %}
                                  <a href="{{ factura.get_absolute_url }}" class="btn btn-success"><span class="glyphicon glyphicon-eye-open"></span></a>
                                  {% endif %}
                                  {% if perms.compras.change_facturadecompra %}
                                  <a href="{{ factura.get_update_url }}" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span></a>
                                  {% endif %}
                                  {% if perms.compras.delete_facturadecompra %}
                                  <a href="{{ factura.get_delete_url }}" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a>
                                  {% endif %}
                            </td>

                          </tr>
                      {% endfor %}
                    </tbody>

                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->
      <footer class="main-footer">
{% include "footer.html" %}
 {% endblock producto %}
{% endblock content %}

proj_compras/templates/compras/solicitudes_lista.html
{% extends "compras/base_compras.html" %}
{% block title %}Compras | Solicitudes{% endblock title %}
{% block content %}
{% include "nav.html" %}
{% block producto %}
    <div class="wrapper">
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Solicitudes de Compra
          </h1>
          <ol class="breadcrumb">
            <li><a href=""><i class="fa fa-dashboard"></i>Inicio</a></li>
            <li class="active">Solicitudes de Compra</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-xs-12">

                <div class="box box-primary">
                  <div class="box-header with-border">
                    {% if perms.compras.add_solicituddecompra %}
                    <h3 class="box-title"><a href="{% url 'compras:nueva_solicitud' %}" class="btn btn-success">
                      Nueva Solicitud
                    </a></h3>
                    {% endif %}
                    <div class="box-tools pull-right">
                      <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div><!-- /.box-tools -->
                  </div><!-- /.box-header -->
                  <div class="box-body">
                  <table id="example1" class="table table-bordered table-striped">
                    <thead>
                     <tr>
                        <th>N°</th>
                        <th>Generada por</th>
                        <th>Fecha Generada</th>
                        <th>Estado</th>
                        <th>Observaciones</th>
                        <th>Acciones</th>
                      </tr>
                    </thead>
                    <tbody>

                     {% for solicitud in solicitudes %}

                        <tr>
                          <td>{{ forloop.counter}}</td>
                          <td>{{ solicitud.generada_por }}</td>
                          <td>{{ solicitud.fecha_generada }} </td>
                          <td>{{ solicitud.get_estado_display }}</td>
                          <td>{{ solicitud.observaciones }}</td>
                          <td class="text-right">
                                  {% if user.is_authenticated %}
                                  <a href="{{ solicitud.get_absolute_url }}" class="btn btn-success"><span class="glyphicon glyphicon-eye-open"></span></a>
                                  {% endif %}
                                  {% if perms.compras.change_solicituddecompra %}
                                  <a href="{{ solicitud.get_update_url }}" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span></a>
                                  {% endif %}
                                  {% if perms.compras.delete_solicituddecompra %}
                                  <a href="{{ solicitud.get_delete_url }}" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a>
                                  {% endif %}
                                  {% if solicitud.estado == "A" %}
                                  <a href="{% url 'compras:nueva_cotizacion' %}?solicitud={{solicitud.id}}" class="btn btn-info"><span class="glyphicon glyphicon-usd"></span></a>
                                  {% endif %}
                            </td>

                          </tr>
                      {% endfor %}
                    </tbody>

                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->
      <footer class="main-footer">
{% include "footer.html" %}
 {% endblock producto %}
{% endblock content %}