compras/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = [

    url(regex=r'^solicitudes/$',
        view=views.SolicitudDeCompraList.as_view(),
        name='lista_solicitudes'
        ),

    url(regex=r'^solicitudes/nueva$',
        view=views.solicitud_de_compra_cru,
        name='nueva_solicitud'
        ),

    url(regex=r'^solicitudes/(?P<pk>[\w-]+)/editar/$',
        view=views.solicitud_de_compra_cru,
        name='editar_solicitud'
        ),

    url(regex=r'^solicitudes/(?P<pk>[\w-]+)/$',
        view=views.detalle_solicitud_de_compra,
        name='detalle_solicitud'
        ),

    url(regex=r'^solicitudes/(?P<pk>[\w-]+)/borrar/$',
        view=views.BorrarSolicitudDeCompra.as_view(),
        name='borrar_solicitud'
        ),

    url(regex=r'^solicitudes/(?P<pk>[\w-]+)/aprobar/$',
        view=views.AprobarSolicitudDeCompra.as_view(),
        name='aprobar_solicitud'
        ),

    url(regex=r'^cotizaciones/$',
        view=views.CotizacionesList.as_view(),
        name='lista_cotizaciones'
        ),

    url(regex=r'^cotizaciones/nueva/$',
        view=views.cotizacion_cru,
        name='nueva_cotizacion'
        ),

    url(regex=r'^cotizaciones/(?P<pk>[\w-]+)/editar/$',
        view=views.cotizacion_cru,
        name='editar_cotizacion'
        ),

    url(regex=r'^cotizaciones/(?P<pk>[\w-]+)/$',
        view=views.detalle_cotizacion,
        name='detalle_cotizacion'
        ),

    url(regex=r'^cotizaciones/(?P<pk>[\w-]+)/borrar/$',
        view=views.BorrarCotizacion.as_view(),
        name='borrar_cotizacion'
        ),

    url(regex=r'^cotizaciones/(?P<pk>[\w-]+)/aprobar/$',
        view=views.AprobarCotizacion.as_view(),
        name='aprobar_cotizacion'
        ),

    url(regex=r'^cotizaciones/(?P<pk>[\w-]+)/rechazar/$',
        view=views.RechazarCotizacion.as_view(),
        name='rechazar_cotizacion'
        ),

    url(regex=r'^ordenes/$',
        view=views.OrdenesList.as_view(),
        name='lista_ordenes'
        ),

    url(regex=r'^ordenes/nueva/$',
        view=views.orden_de_compra_cru,
        name='nueva_orden'
        ),

    url(regex=r'^ordenes/(?P<pk>[\w-]+)/$',
        view=views.detalle_orden,
        name='detalle_orden'
        ),

    url(regex=r'^ordenes/(?P<pk>[\w-]+)/editar/$',
        view=views.orden_de_compra_cru,
        name='editar_orden'
        ),

    url(regex=r'^ordenes/(?P<pk>[\w-]+)/borrar/$',
        view=views.BorrarOrdenDeCompra.as_view(),
        name='borrar_orden'
        ),

    url(regex=r'^facturas/$',
        view=views.FacturasList.as_view(),
        name='lista_facturas'
        ),

    url(regex=r'^facturas/nueva/$',
        view=views.CrearFactura.as_view(),
        name='nueva_factura'
        ),

    url(regex=r'^facturas/(?P<pk>[\w-]+)/$',
        view=views.DetalleFactura.as_view(),
        name='detalle_factura'
        ),

    url(regex=r'^facturas/(?P<pk>[\w-]+)/editar/$',
        view=views.ActualizarFactura.as_view(),
        name='editar_factura'
        ),

    url(regex=r'^facturas/(?P<pk>[\w-]+)/borrar/$',
        view=views.BorrarFactura.as_view(),
        name='borrar_factura'
        ),
]

proj_compras/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings


admin.autodiscover()


urlpatterns = patterns(
    '',

    url(r'^admin/', include(admin.site.urls)),

    #login-users
    url(r'^',
        include('usuarios.urls',  namespace='usuarios')
        ),

    # Login/Logout URLs
    #(r'^login/$',
    #    'django.contrib.auth.views.login', {'template_name': 'login.html'}
    #),

    #(r'^logout/$',
    #    'django.contrib.auth.views.logout', {'next_page': '/login/'}
    #),

    url(r'^proveedores/',
        include('proveedores.urls', namespace='proveedores')
        ),

    url(r'^contactos/',
        include('contactos.urls', namespace='contactos')
        ),

    url(r'^mercaderias/',
        include('mercaderias.urls', namespace='mercaderias')
        ),

    url(r'^compras/',
        include('compras.urls', namespace='compras')
        ),
)
#Added for debug toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

proveedores/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = [

    url(regex=r'^$',
        view=views.ProveedoresList.as_view(),
        name='lista'
        ),

    url(regex=r'^nuevo/$',
        view=views.proveedor_cru,
        name='nuevo'
        ),

    url(regex=r'^(?P<uuid>[\w-]+)/editar/$',
        view=views.proveedor_cru,
        name='editar'
        ),

    url(regex=r'^(?P<pk>[\w-]+)/borrar/$',
        view=views.BorrarProveedor.as_view(),
        name='borrar'
        ),

    url(regex=r'^(?P<uuid>[\w-]+)/$',
        view=views.detalle_proveedor,
        name='detalle'
        ),

]

contactos/models.py
from django.db import models

from shortuuidfield import ShortUUIDField

from proveedores.models import Proveedor


# Create your models here.
class Contacto(models.Model):
    uuid = ShortUUIDField(unique=True)
    proveedor = models.ForeignKey(Proveedor,
                                  on_delete=models.CASCADE,
                                  blank=True,
                                  null=True
                                  )
    nombre = models.CharField(max_length=80)
    email = models.EmailField(blank=True)
    #FIXME Cantidad dinamica de telofonos?
    telefono = models.CharField(max_length=40, blank=True)
    #telefono_2 = models.CharField(max_length=40, blank=True)
    direccion = models.CharField(max_length=80, blank=True)
    #FIXME Se podria agregar una tabla direccion con ciudad, provincia, etc
    #direccion_2 = models.CharField(max_length=80, blank=True)
    pagina_web = models.URLField(blank=True)
    detalles = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = 'contactos'

    def __str__(self):
        return "%s" % self.nombre

    @models.permalink
    def get_absolute_url(self):
        return 'contactos:detalle', [self.uuid]

    @models.permalink
    def get_update_url(self):
        return 'contactos:editar', [self.uuid]

    @models.permalink
    def get_delete_url(self):
        return 'contactos:borrar', [self.id]

proveedores/models.py
from django.db import models
from django.utils.timezone import now

from shortuuidfield import ShortUUIDField
from proj_compras.constants import CONDICION_IVA_CHOICES
from proj_compras.constants import NO_ESPECIFICA


# Create your models here.
class Proveedor(models.Model):
    uuid = ShortUUIDField(unique=True)
    nombre_fiscal = models.CharField(max_length=80)
    nombre_fantasia = models.CharField(max_length=80, blank=True)
    fecha_alta = models.DateField(default=now, blank=True)
    cuit = models.CharField(max_length=25, blank=True)
    margen_ganancia = models.SmallIntegerField(blank=True, null=True)
    condicion_iva = models.CharField(max_length=5,
                                     choices=CONDICION_IVA_CHOICES,
                                     default=NO_ESPECIFICA)

    class Meta:
        verbose_name_plural = 'proveedores'

    def display_name(self):
        if self.nombre_fantasia:
            return self.nombre_fantasia
        return self.nombre_fiscal

    def __str__(self):
        return "%s" % self.display_name()

    @models.permalink
    def get_absolute_url(self):
        return 'proveedores:detalle', [self.uuid]

    @models.permalink
    def get_update_url(self):
        return 'proveedores:editar', [self.uuid]

    @models.permalink
    def get_delete_url(self):
        return 'proveedores:borrar', [self.id]

proveedores/forms.py
from django import forms

from .models import Proveedor
from proj_compras.constants import CONDICION_IVA_CHOICES
#from proj_compras.constants import RESPONSABLE_INSCRIPTO


class ProveedorForm(forms.ModelForm):
    class Meta:
        model = Proveedor

        fields = ('nombre_fiscal', 'nombre_fantasia', 'fecha_alta',
                  'cuit', 'condicion_iva', )

        widgets = {
            'condicion_iva': forms.Select(attrs={
                            'placeholder': 'Condición IVA',
                            'class': 'form-control'})
        }

    nombre_fantasia = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={'placeholder': 'Nombre de Fantasía'})
    )
    nombre_fiscal = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={'placeholder': 'Nombre Fiscal'})
    )
    fecha_alta = forms.DateField(
        required=False,
        label='Fecha De Alta',
        widget=forms.DateInput(attrs={
                               'placeholder': 'Fecha de Alta',
                               'class': 'form-control',
                               'id': 'FechaAlta'})
    )
    cuit = forms.CharField(
        required=False,
        label='CUIT',
        widget=forms.TextInput(attrs={'placeholder': 'CUIT'})
    )
    #margen_ganancia = forms.IntegerField(
    #    widget=forms.NumberInput(attrs={'placeholder': 'form-control'})
    #)

proveedores/views.py
from django.views.generic import ListView, DeleteView
from django.contrib.auth.decorators import login_required, permission_required
from django.utils.decorators import method_decorator
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.core.urlresolvers import reverse
from django.db.models import Q
from braces.views import LoginRequiredMixin, PermissionRequiredMixin


from .models import Proveedor
from contactos.models import Contacto
from .forms import ProveedorForm


# Create your views here.
class ProveedoresList(LoginRequiredMixin, ListView):
    model = Proveedor
    template_name = 'proveedores/proveedores_lista.html'
    #This name can then be later used in templates.
    context_object_name = 'proveedores'
    redirect_field_name = '/login/'


@login_required()
def detalle_proveedor(request, uuid):
    #The uuid object is passed to the view via the URL configuration
    proveedor = Proveedor.objects.get(uuid=uuid)

    contactos = Contacto.objects.filter(proveedor=proveedor)

    variables = {
        'proveedor': proveedor,
        'contactos': contactos
    }

    return render(request, 'proveedores/detalle_proveedor.html', variables)


@login_required()
def proveedor_cru(request, uuid=None):

    if uuid:
        if not request.user.has_perm('proveedores.change_proveedor'):
            return HttpResponseForbidden()
        proveedor = get_object_or_404(Proveedor, uuid=uuid)
    else:
        if not request.user.has_perm('proveedores.add_proveedor'):
            return HttpResponseForbidden()
        proveedor = Proveedor()

    if request.POST:
        form = ProveedorForm(request.POST, instance=proveedor)
        if form.is_valid():
            form.save()
            redirect_url = reverse(
                'proveedores:detalle',
                args=(proveedor.uuid,)
            )
            return HttpResponseRedirect(redirect_url)
    else:
        form = ProveedorForm(instance=proveedor)

    variables = {
        'form': form,
        'proveedor': proveedor,
    }

    template = 'proveedores/proveedores_create_update.html'

    return render(request, template, variables)


class BorrarProveedor(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Proveedor
    template_name = 'proveedores/eliminar_proveedor.html'
    permission_required = 'proveedores.delete_proveedor'
    raise_exception = True
    success_url = '/proveedores/'

proj_compras/templates/proveedores/base_proveedores_lista.html
{% extends "base.html" %}
{% load staticfiles %}
{% block css %}

   <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="/static/plugins/datatables/dataTables.bootstrap.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/static/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/static/dist/css/skins/skin-blue.min.css">

    <!-- DatePicker -->
    <link src="/static/plugins/datepicker/datepicker3.css" rel="stylesheet" type="text/css"></link>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
{% endblock css %}
{% block js %}

    <!-- jQuery 2.1.4 -->
    <script src="/static/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <!-- Bootstrap 3.3.5 -->
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    <!-- DataTables -->
    <script src="/static/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="/static/plugins/datatables/dataTables.bootstrap.min.js"></script>
    <!-- SlimScroll -->
    <script src="/static/plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="/static/plugins/fastclick/fastclick.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/static/dist/js/app.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/static/dist/js/demo.js"></script>
    <!-- page script -->
    <script>
      $(function () {
        $("#example1").DataTable();
        $('#example2').DataTable({
          "paging": true,
          "lengthChange": false,
          "searching": false,
          "ordering": true,
          "info": true,
          "autoWidth": false
        });
      });
    </script>

    <!-- calendario -->
       <!-- DATEPICKER --> <script src="/static/plugins/datepicker/bootstrap-datepicker.js" type="text/javascript"></script>
       <script>
       $('#FechaAlta').datepicker({
        autoclose: true,
        todayHighlight: true
        });

  </script>
<!--endcalendario-->

<script src="/static/js/app.js"></script>

{% endblock js %}

proj_compras/templates/proveedores/detalle_proveedor.html
{% extends "proveedores/base_proveedores_lista.html" %}
{% block title %}Proveedores{% endblock title %}
{% block content %}
{% include "nav.html" %}
{% block producto %}
<div class="wrapper">
      <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
        <!-- Main content -->
    <section class="content">
      <!-- START ALERTS AND CALLOUTS -->
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">

            <div class="box-header with-border">
                <a href="javascript:history.go(-1);" class="btn btn-success">
                    <span class="glyphicon glyphicon-chevron-left"></span> Regresar
                </a>
                    <div class="box-tools pull-right">
                      <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div><!-- /.box-tools -->
            </div><!-- /.box-header -->
              <div class="box-body">
                  <table class="table table-striped table table-hover ">
                        <tbody>
                              <tr class="success">
                                  <td><strong>Nombre Fiscal:</strong></td>
                                  <td>{{ proveedor.nombre_fiscal }}</td>
                              </tr>
                              <tr class="success">
                                  <td><strong>Nombre de Fantasía:</strong></td>
                                  <td>{{ proveedor.nombre_fantasia }} </td>
                               </tr>
                               <tr class="success">
                                  <td><strong>CUIT:</strong></td>
                                  <td>{{ proveedor.cuit }}</td>
                               </tr>
                                                           <tr class="success">
                                  <td><strong>Condicion IVA:</strong></td>
                                  <td>{{ proveedor.get_condicion_iva_display }}</td>
                               </tr>
                               <tr class="success">
                                  <td><strong>Fecha de Alta:</strong> </td>
                                  <td>{{ proveedor.fecha_alta}}</td>
                               </tr>
                        </tbody>
                    </table>

              </div><!-- /.box -->
          </div><!-- /.col -->
        </div><!-- /.row -->
        <div id="cd-container" class="row">
            <div class="col-md-12">
                <div class="box box-info">
                     <div class="box-header with-border">
                        <h2 class="page-header"> Contactos </h2>
                        <div class="box-tools pull-right">
                            <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        </div><!-- /.box-tools -->
                    </div><!-- /.box-header -->
                    <div id="cd-body" class="box-body">
                        {% if perms.contactos.add_contacto %}
                        <a href="{% url 'contactos:nuevo' %}?proveedor={{ proveedor.id }}" id="nuevo-contacto" class="btn btn-success"> <span class="glyphicon glyphicon-chevron"></span> Nuevo Contacto</a>
                        {% endif %}
                        <table id="cd-table" class="table table-responsive table table-hover">
                            <tbody>
                                <tr>
                                    <th> Nombre </th>
                                    <th> Teléfono </th>
                                    <th> Email </th>
                                    <th> Direccion </th>
                                    <th> Web </th>
                                    <th> Acciones </th>
                                </tr>
                                {% for contacto in contactos %}
                                    {% include 'contactos/item_contacto.html' %}
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div> <!-- box -->
            </div> <!-- col -->
        </div> <!-- row -->
    </section><!-- /.content -->
  </div><!-- /.content-wrapper -->

{% include "footer.html" %}
{% endblock producto %}
{% endblock content %}

proj_compras/templates/proveedores/eliminar_proveedor.html
{% extends "proveedores/base_proveedores_lista.html" %}
{% block title %}Eliminar Proveedor{% endblock title %}
{% block content %}
{% include "nav.html" %}
{% block producto %}
<div class="wrapper">
      <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
        <!-- Main content -->
    <section class="content">
      <!-- START ALERTS AND CALLOUTS -->
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">
            <div class="box-header with-border">
              <i class="fa fa-bullhorn"></i>
            </div><!-- /.box-header -->
              <div class="box-body">
                  <div class="callout callout-danger">
                    <h1> Eliminar</h1>
                    <form method="POST">
                    {% csrf_token %}
                      <p class="coloreliminar">¿Desea eliminar al proveedor "{{ object.nombre_fiscal }}?</p>
                      <input type="submit" value="Sí" class="btn btn-warning">
                      <a href="{% url 'proveedores:lista' %}" class="btn btn-info">No</a>
                    </form>
                  </div>
              </div><!-- /.box -->
          </div><!-- /.col -->
        </div><!-- /.row -->
    </section><!-- /.content -->
  </div><!-- /.content-wrapper -->

{% include "footer.html" %}
 {% endblock producto %}
{% endblock content %}

proj_compras/templates/proveedores/proveedores_create_update.html
{% extends "proveedores/base_proveedores_lista.html" %}
{% block title %}Proveedores{% endblock title %}
{% block content %}
{% include "nav.html" %}
{% block producto %}
<div class="wrapper">
      <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
         <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Proveedores
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i>Inicio</a></li>
            <li><a href="{% url 'proveedores:lista' %}">Proveedores</a></li>
            <li class="active">Nuevo/Editar Proveedor</li>
          </ol>
        </section>
        <!-- Main content -->
    <section class="content">
      <!-- START ALERTS AND CALLOUTS -->
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">
            <div class="box-header with-border">

              <a href="javascript:history.go(-1);" class="btn btn-success">
                    <span class="glyphicon glyphicon-chevron-left"></span> Regresar
              </a>

              <div class="box-tools pull-right">
                  <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
              </div><!-- /.box-tools -->

            </div><!-- /.box-header -->
              <div class="box-body">

                    <div class="row">
                      <div class="col-lg-12">
                        <form class="form-horizontal" method="post">
                            {% csrf_token %}
                            <div class="row">

                                <div class="col-xs-12 col-sm-10">
                                    <div class="form-group has-success has-feedback  {% if form.nombre_fiscal.errors %} has-error {% endif %}">
                                        <label class="control-label col-sm-2" for="inputSuccess3">{{ form.nombre_fiscal.label_tag }}</label>
                                        <div class="col-sm-6">
                                            <input type="text" name="nombre_fiscal" class="form-control" value='{% if form.nombre_fiscal.value %}{{ form.nombre_fiscal.value }}{% endif %}' data-toggle="tooltip" data-placement="top" title='{{ form.nombre_fiscal.errors.as_text}}' autofocus='true' id="disabledInput" type="text" >
                                        </div>
                                    </div>

                                    <div class="form-group has-success has-feedback  {% if form.nombre_fantasia.errors %} has-error {% endif %}">
                                        <label class="control-label col-sm-2" for="inputSuccess3">{{ form.nombre_fantasia.label_tag }}</label>
                                        <div class="col-sm-6">
                                            <input type="text" id="disabledTextInput" name="nombre_fantasia" class="form-control" value='{% if form.nombre_fantasia.value %}{{ form.nombre_fantasia.value }}{% endif %}' data-toggle="tooltip" data-placement="top" title='{{ form.nombre_fantasia.errors.as_text}}' autofocus='true'>
                                        </div>
                                    </div>

                                    <div class="form-group has-success has-feedback  {% if form.cuit.errors %} has-error {% endif %}">
                                        <label class="control-label col-sm-2" for="inputSuccess3">{{ form.cuit.label_tag }}</label>
                                         <div class="col-sm-6">
                                            <input type="text" id="disabledTextInput" name="cuit" class="form-control" value='{% if form.cuit.value %}{{ form.cuit.value }}{% endif %}' data-toggle="tooltip" data-placement="top" title='{{ form.cuit.errors.as_text}}' autofocus='true'>
                                        </div>
                                    </div>


                                    <div class="form-group has-success has-feedback  {% if form.condicion_iva.errors %} has-error {% endif %}">
                                        <label class="control-label col-sm-2" for="inputSuccess3">{{ form.condicion_iva.label_tag }}</label>
                                        <div class="col-sm-6">
                                            {{ form.condicion_iva }}
                                        </div>
                                    </div>
                                    <div class="form-group has-success has-feedback  {% if form.fecha_alta.errors %} has-error {% endif %}">
                                        <label class="control-label col-sm-2" for="inputSuccess3">{{ form.fecha_alta.label_tag }}</label>
                                        <div class="col-sm-6">
                                            <div class="input-group">
                                          <div class="input-group-addon">
                                              <i class="fa fa-calendar"></i>
                                          </div>
                                          {{ form.fecha_alta }}
                                      </div>
                                        </div>
                                       </div>
                                </div>
                            </div> <!--<div class="row"> -->
                                <div class="panel-footer color-footer">
                                    <button type="submit" class="btn btn-primary">
                                                 Grabar
                                    </button>
                                </div>
                        </form>
                      </div>
                    </div><!--/.row-->
            </div><!-- /.box body -->
          </div><!-- /.box info -->
          </div><!--col-->
        </div><!-- /.row -->
    </section><!-- /.content -->
  </div><!-- /.content-wrapper -->
{% include "footer.html" %}
 {% endblock producto %}
{% endblock content %}

proj_compras/templates/proveedores/proveedores_lista.html
{% extends "proveedores/base_proveedores_lista.html" %}
{% block title %}Proveedores{% endblock title %}
{% block content %}
{% include "nav.html" %}
{% block producto %}
    <div class="wrapper">
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Proveedores
          </h1>
          <ol class="breadcrumb">
            <li><a href=""><i class="fa fa-dashboard"></i>Inicio</a></li>
            <li class="active">Proveedores</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-xs-12">

                <div class="box box-primary">
                  <div class="box-header with-border">
                    {% if perms.proveedores.add_proveedor %}
                    <h3 class="box-title"><a href="{% url 'proveedores:nuevo' %}" class="btn btn-success">
                      Nuevo Proveedor
                    </a></h3>
                    {% endif %}
                    <div class="box-tools pull-right">
                      <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div><!-- /.box-tools -->
                  </div><!-- /.box-header -->
                  <div class="box-body">
                  <table id="example1" class="table table-bordered table-striped">
                    <thead>
                     <tr>
                        <th>N°</th>
                        <th>Nombre</th>
                        <th>CUIT</th>
                        <th>Condicion IVA</th>
                        <th>Fecha de Alta</th>
                        <th>Acciones</th>
                      </tr>
                    </thead>
                    <tbody>

                     {% for proveedor in proveedores %}

                        <tr>
                          <td>{{ forloop.counter}}</td>
                          <td>{{ proveedor.display_name }}</td>
                          <td>{{ proveedor.cuit }} </td>
                          <td>{{ proveedor.get_condicion_iva_display }}</td>
                          <td>{{ proveedor.fecha_alta}}</td>
                          <td class="text-right">
                                  <a href="{{ proveedor.get_absolute_url }} " class="btn btn-success"><span class="glyphicon glyphicon-eye-open"></span></a>

                                  {% if perms.proveedores.change_proveedor %}
                                  <a href="{{ proveedor.get_update_url }}" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span></a>
                                  {% endif %}
                                  {% if perms.proveedores.delete_proveedor %}
                                  <a href="{{ proveedor.get_delete_url }}" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a>
                                  {% endif %}
                            </td>

                          </tr>
                      {% endfor %}
                    </tbody>

                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->
      <footer class="main-footer">
{% include "footer.html" %}
 {% endblock producto %}
{% endblock content %}